---
- hosts: elixir
  user: vagrant
  gather_facts: no
  tasks:
    - name: Update packages
      sudo: yes
      apt: update_cache=yes
      tags:
        - update

    - name: Dependencies
      sudo: yes
      apt:
        pkg: "{{ item }}"
        state: installed
      with_items:
        - build-essential
        - libncurses5-dev
        - openssl
        - libssl-dev
        - fop
        - xsltproc
        - unzip
      tags:
        - update

    - name: Get Erlang r17
      get_url: url=http://erlang.org/download/otp_src_17.0.tar.gz dest=/tmp/ force=true
      tags:
        - erlang

    - name: Extract Erlang
      command: tar xf /tmp/otp_src_17.0.tar.gz chdir=/tmp/
      tags:
        - erlang

    - name: Configure Erlang
      sudo: true
      command: ./configure chdir=/tmp/otp_src_17.0/
      tags:
        - erlang

    - name: Install Erlang
      sudo: true
      command: make install chdir=/tmp/otp_src_17.0/
      tags:
        - erlang

    - name: Get Elixir
      get_url: url=https://github.com/elixir-lang/elixir/archive/v1.0.0.tar.gz dest=/tmp/v1.0.0.tar.gz force=true
      tags:
        - elixir

    - name: Extract Elixir
      command: tar xf /tmp/v1.0.0.tar.gz
        chdir=/tmp/ 
      tags:
        - elixir

    - name: Install Elixir
      sudo: yes
      command: make chdir=/tmp/elixir-1.0.0
      tags:
        - elixir

    - command: make install chdir=/tmp/elixir-1.0.0
      sudo: yes
      tags:
        - elixir

